-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 11:06:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spring_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spring_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spring_db` DEFAULT CHARACTER SET utf8 ;
USE `spring_db` ;

-- -----------------------------------------------------
-- Table `spring_db`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_db`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NULL,
  `description` VARCHAR(500) NULL,
  `status` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `date_created` VARCHAR(45) NULL,
  `date_updated` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
